version: '3.9'
services:
  template:
    build:
      context: .
    ports:
      - 8080:80
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      MONGO_HOST: mongo
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    hostname: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo: