name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

  workflow_dispatch:

jobs:
  integrate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.101

      - name: Unit Test
        run: dotnet test -c Debug

      - name: Mutation Test
        run: |
          dotnet tool install -g dotnet-stryker
          cd Tests/Unit
          dotnet stryker -p Application.csproj
          dotnet stryker -p Domain.csproj